pipeline {

    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK'
    }

    stages {

        stage('Checkout') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/Akashraj44/capstone_project.git'
            }
        }

        stage('Clean') {

            steps {

                dir('Capstone_Project') {

                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {

            steps {

                dir('Capstone_Project') {

                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {

            steps {

                dir('Capstone_Project') {

                    bat 'mvn test'
                }
            }
        }

        stage('Package') {

            steps {

                dir('Capstone_Project') {

                    bat 'mvn package'
                }
            }
        }
    }

    post {

        success {

            echo 'Guru99 Framework Build Successful'
        }

        failure {

            echo 'Guru99 Framework Build Failed'
        }

        always {

            echo 'Pipeline Execution Completed'
        }
    }
}